export enum AudioAIDs {
  STEP = "STEP",
  PICKUP_POWERUP = "PICKUP_POWERUP",
  PICKUP_POSITIVE = "PICKUP_POSITIVE",
  PICKUP_NEGATIVE = "PICKUP_NEGATIVE",
  PICKUP_LOSS = "PICKUP_LOSS",
  LEVEL_UP = "LEVEL_UP",
}
